### ISSUE TITLE
Missing integration documentation

### ISSUE THREAD

**Issue by kmarushchakItomy** [faceki/react-native-sdk-v2#1]
Hi. What is the proper way to install and integrate this SDK into React Native project? Unfortunately the documentation lacks such information and the source code looks more like an example of how would one implement KYC using FaceKI REST API service.

**Comment by haziqfaceki** [comment]
Hi, @kmarushchakItomy.

This is a Starter Kit for Faceki APIs in the React Native Application. You can simply clone and customize it as per your needs.
